"""The layered, schema-validated quirks database (DESIGN.md 4)."""

from __future__ import annotations

from .errors import ConfigError
from .loader import (
    AddedRequirement,
    Additions,
    ConfigTree,
    FeedstockConfig,
    Layered,
    MappingLayer,
    find_config_root,
    load_config,
)
from .schema import (
    AddRequirements,
    ArchiveUpstream,
    BuiltEverywhere,
    CMakeUpstream,
    Defaults,
    DynamicPolicy,
    EsmfUpstream,
    ExtrasAsOutputs,
    Family,
    Feedstock,
    GitHubUpstream,
    ManualUpstream,
    NoUpstream,
    Output,
    OutputRun,
    Override,
    Quirks,
    RecipeOwned,
    RemovalPolicy,
    RunConstraint,
    SourceVersionPolicy,
    TestMatrixPolicy,
    TrustLevel,
    Upstream,
    VariantCondition,
)

__all__ = [
    "AddRequirements",
    "AddedRequirement",
    "Additions",
    "ArchiveUpstream",
    "BuiltEverywhere",
    "CMakeUpstream",
    "ConfigError",
    "ConfigTree",
    "Defaults",
    "DynamicPolicy",
    "EsmfUpstream",
    "ExtrasAsOutputs",
    "Family",
    "Feedstock",
    "FeedstockConfig",
    "GitHubUpstream",
    "Layered",
    "ManualUpstream",
    "MappingLayer",
    "NoUpstream",
    "Output",
    "OutputRun",
    "Override",
    "Quirks",
    "RecipeOwned",
    "RemovalPolicy",
    "RunConstraint",
    "SourceVersionPolicy",
    "TestMatrixPolicy",
    "TrustLevel",
    "Upstream",
    "VariantCondition",
    "find_config_root",
    "load_config",
]
