"""Telling swage's own comments apart from a maintainer's (DESIGN.md 6.1).

swage renders requirements sections, so the comments inside them are of two
kinds and they need opposite treatment. The ones swage authors are regenerated
from the plan every run; everything else was written by a person, and is
preserved and re-anchored to the requirement below it.

Getting the split wrong is not symmetric. Treating a maintainer's note as
swage's loses it -- once, silently, and only the author would notice. Treating
one of swage's own as a maintainer's *duplicates* it, on every affected
feedstock, on the first run after the mistake.

**This is a versioning problem rather than a parsing one, and that is the whole
reason the module exists.** A comment swage no longer writes is still swage's:
`# more restrictive for python >=3.14` was generated by a tool, no human chose
it, and re-anchoring it as prose would leave a recipe with two notes above one
dependency saying the same thing differently. Both retired wordings are below,
and they are not dead code -- 53 recipes in the maintainer's checkouts carry
them today, and every one is a feedstock swage has not yet run on.

> **Retiring a convention means adding to `_RETIRED`, never editing
> `_CURRENT`.** The list only grows. It is cheap to keep a pattern for a
> wording nothing emits any more, and the cost of dropping one is paid across
> the fleet at once.
"""

from __future__ import annotations

import re

__all__ = ["is_swage_authored", "maintainer_comments"]

#: Comments swage generates today, from `assemble` and `reconcile`.
_CURRENT = (
    # `# from the bqstorage extra` -- an extra's block header (DESIGN.md 6).
    re.compile(r"^#\s*from the \S+ extra$"),
    # `# start pyhive[hive-pure-sasl]` / `# end pyhive[hive-pure-sasl]` --
    # the embedded-extras round-trip markers.
    re.compile(r"^#\s*(?:start|end) \S+$"),
    # The marker note, in its three shapes: `# tightest of upstream's floors
    # (python >=3.14)`, the same for a ceiling, and both at once where the two
    # bounds came from different declarations. One pattern rather than three,
    # because a note swage writes and does not recognize is a note it
    # duplicates on the next run.
    re.compile(r"^#\s*tightest of upstream's (?:floors|ceilings)\b.*$"),
    # `# celery[redis] needs nothing extra on conda-forge` -- the caption on a
    # dependency whose extra config settled as pulling nothing in. It replaces
    # the empty `# start`/`# end` pair the prior tools wrote, and that pair is
    # matched by the marker pattern above, so the changeover costs no entry in
    # `_RETIRED`.
    #
    # The `name[extra]` shape is required, which is what keeps the pattern off
    # a maintainer's sentence that happens to end the same way.
    re.compile(r"^#\s*\S+\[[^\]]+\] needs nothing extra on conda-forge$"),
)

#: Wordings swage used to generate, or that the tools it replaces generated for
#: it. Recognized so a first run replaces them instead of preserving them
#: alongside their successor. See the module docstring: this list only grows.
_RETIRED = (
    # The airflow tool's marker note, and swage's until the google-cloud corpus
    # showed the two tools disagreeing (DESIGN.md 3.3.1).
    re.compile(r"^#\s*more restrictive for .+$"),
    # The google-cloud tool's spelling of the same note.
    re.compile(r"^#\s*more restrictive constraint for .+$"),
    # A third spelling, on `google-ads` and -- by a code search across the
    # whole conda-forge organization -- nowhere else. Two shapes, because that
    # recipe carries both: `# strictest constraint for python >=3.13` where one
    # declaration won outright, and `# strictest lower bound for python >=3.13;
    # upper bound from python >=3.10` where the floor and the ceiling came from
    # different declarations.
    #
    # Found by reading what swage would push, not by any test and not by the
    # fleet comparison, which classified the addition as a rewording it already
    # knew about. Without these, the first run on that feedstock writes swage's
    # note above each of seven requirements and leaves the old one underneath.
    re.compile(r"^#\s*strictest constraint for .+$"),
    re.compile(r"^#\s*strictest lower bound for .+$"),
    # `# graphviz extra` -- the hand-written shorthand for an extra's block
    # header, in the airflow, google-auth and google-cloud-bigquery recipes.
    # It says exactly what `# from the graphviz extra` says, so swage replaces
    # it rather than rendering its own header beside it.
    #
    # Exactly one token before `extra`, which is what keeps the pattern off a
    # sentence that merely ends in the word: `# conda-forge package includes
    # google-auth[pyopenssl] extra` is a maintainer's note and stays one.
    re.compile(r"^#\s*\S+ extra$"),
    # `# google-cloud-aiplatform[evaluation]` -- the hand-written label above an
    # expansion block, in the airflow google provider's recipe. It says what
    # `# start google-cloud-aiplatform[evaluation]` says, so preserving it
    # would leave that recipe carrying both: a label swage does not write,
    # sitting beside the marker pair it does.
    #
    # The whole comment has to be one `name[extra]` token, which keeps it off a
    # maintainer's sentence that merely mentions a requirement.
    re.compile(r"^#\s*\S+\[[^\]]+\]$"),
)


def is_swage_authored(comment: str) -> bool:
    """Whether this comment is one swage renders rather than preserves.

    A blank line is never swage's: it is a maintainer's spacing, and the recipe
    model round-trips it as an empty string.
    """
    if not comment:
        return False
    stripped = comment.strip()
    return any(pattern.match(stripped) for pattern in (*_CURRENT, *_RETIRED))


def maintainer_comments(comments: tuple[str, ...]) -> tuple[str, ...]:
    """The comments above a requirement that swage did not write."""
    return tuple(comment for comment in comments if not is_swage_authored(comment))
